# -*- coding: utf-8 -*-
{
    'name': 'AnetZ Hotel Management',
    'version': '17.0.1.2.4',
    'category': 'Services',
    'summary': """Hotel Management, Odoo Hotel Management, Hotel, Room Booking odoo, Amenities Odoo, Event management, Rooms, Events, Food, Booking, Odoo Hotel, Odoo17, Odoo Apps""",
    'description': """The module helps you to manage rooms, amenities, 
     services, food, events and vehicles. End Users can book rooms and reserve 
     foods from hotel.""",
    'author': 'Jannet Global Communications Pvt Ltd.',
    'company': 'Jannet Global Communications Pvt Ltd.',
    'maintainer': 'Jannet Global Communications Pvt Ltd.',
    'website': 'https://antsyz.com',
    'depends': ['account', 'event', 'fleet', 'lunch'],
    'data': [
        'security/groups.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_data_sequence.xml',
        'views/account_move_views.xml',
        'views/hotel_menu_views.xml',
        'views/hotel_amenity_views.xml',
        'views/hotel_service_views.xml',
        'views/hotel_floor_views.xml',
        'views/hotel_room_views.xml',
        'views/lunch_product_views.xml',
        'views/fleet_vehicle_model_views.xml',
        'views/room_booking_views.xml',
        'views/maintenance_team_views.xml',
        'views/maintenance_request_views.xml',
        'views/cleaning_team_views.xml',
        'views/cleaning_request_views.xml',
        'views/food_booking_line_views.xml',
        'views/dashboard_view.xml',
        'wizard/room_booking_detail_views.xml',
        'wizard/sale_order_detail_views.xml',
        'views/reporting_views.xml',
        'report/room_booking_reports.xml',
        'report/sale_order_reports.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'anetz_hotel_management/static/src/js/action_manager.js',
            'anetz_hotel_management/static/src/css/dashboard.css',
            'anetz_hotel_management/static/src/js/dashboard_action.js',
            'anetz_hotel_management/static/src/xml/dashboard_templates.xml',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
